ジャンケンアプリ再提出
shinonome-inc/mobile_sakai pull request #10
Opened 2020-11-01 09:16 UTC by yasyun

2020-11-02 05:57 UTC, your-chance reviewed
じゃんけんのロジック部分とアニメーションはいい感じだと思います．
次は，課題の参考動画のようにボタン押したらアニメーションが流れ，勝敗が決まるようにしてみましょう！

2020-11-02 05:57 UTC, your-chance commented on JyankenApp_iOS/JyankenApp/ViewController.swift
> +    }
ローカル変数として使わないプロパティ部分は最初に宣言するといいと思います．

また，
①IBOutlet等の宣言
②プロパティ
③viewDidLoad()
④IBAction
⑤その他の処理
の順に書くと良いと思います．

2020-11-02 05:57 UTC, your-chance commented on JyankenApp_iOS/JyankenApp/ViewController.swift
> +        }
cpではなくcpHandではないですか？
キャメルケースで書くといいと思います．

2020-11-02 05:57 UTC, your-chance commented on JyankenApp_iOS/JyankenApp/ViewController.swift
> +    }
`let hand = enemyHand[dispImageNo]`
`let image = UIImage(named: hand)`
は，他に使わないのであれば一つにまとめていいと思います．

2020-11-14 12:48 UTC, ShuheiYoshidaJP commented
もしかしたら初めてコードを見る人は
type = 0ってなんやねんってなる可能性もあるかもしれないので
せっかくenumをセットしてるなら、活用してあげてもいいかなとおもいます。
![ 2020-11-14 21 46 59](https://user-images.githubusercontent.com/62702170/99147267-edcbcf00-26c2-11eb-900e-71e4ea0e7f73.png)

2020-11-16 17:35 UTC, your-chance commented on JyankenApp_iOS/JyankenApp/ViewController.swift
> +    let paper = UIImage(named:"paper")!
これどこかで使ってる？

2020-11-16 19:26 UTC, your-chance reviewed
アニメーション中にボタン操作を行うとアニメーションが止まらなくなるバグがあるので、連続でボタン操作が行われた時も正常にジャンケンが行えるようにしましょう！

2020-11-16 19:26 UTC, KohkiKimino commented on JyankenApp_iOS/JyankenApp/ViewController.swift
> +    let paper = UIImage(named:"paper")!
これどこかで使ってますか？

2020-11-16 19:26 UTC, KohkiKimino commented on JyankenApp_iOS/JyankenApp/ViewController.swift
> +            enemy.image = image
`enemy.image = UIImage(named: enemyHand[dispImageNo])`にまとめていいと思います！

2020-11-16 19:26 UTC, KohkiKimino commented on JyankenApp_iOS/JyankenApp/ViewController.swift
> +        }
`enemy.image = UIImage(named: enemyHand[cp])`
にまとめていいと思います！
switch ansを無くして、`case (let handId, let cpHand) where handId == cpHand: result.text = "draw"`のようにしていいと思います。またここで、直接"draw"を代入するのではなく、enum Resultを活用してみましょう！

2020-11-18 19:17 UTC, your-chance reviewed
良い感じの動作になったと思います！
次は、デバイスによってレイアウトが変わってしまうのを直しましょう！(AutoLayout)
![スクリーンショット 2020-11-19 4 13 33](https://user-images.githubusercontent.com/56348011/99576957-ff440c80-2a1d-11eb-8982-e6bd91210740.png)

2020-11-18 19:17 UTC, KohkiKimino commented on JyankenApp_iOS/JyankenApp/ViewController.swift
> +        let cp = Int.random(in: Hand.rock.rawValue..<3)
`let cp = Int.random(in: Hand.rock.rawValue..<3)`にするなら、
`let cp = Int.random(in: Hand.rock.rawValue...Hand.paper.rawValue)`
でいいと思います！

2020-11-18 19:17 UTC, KohkiKimino commented on JyankenApp_iOS/JyankenApp/ViewController.swift
> +    var flag = 0
youHand使ってますか？typeをyouHandにするのはどうですか？
スイッチするならbool値の方がわかりやすい気がします！

2020-11-28 09:09 UTC, ShuheiYoshidaJP commented
見た感じだと
resultLabelだけhorizontally in containerとvertically in containerを使っていますね
オススメとしては
他のパーツもhorizontally in containerとvertically in containerを使うといいのですが
resultLabelをだけを基準にレイアウトを決めて行きたい場合は
他のパーツのalighment constraitの参照先をresultLabelに指定してあげてください
以下に例を示します
before
![ 2020-11-28 17 54 26](https://user-images.githubusercontent.com/62702170/100498070-ff24d900-31a2-11eb-8f08-f5c4898c8531.png)
after
![ 2020-11-28 17 58 40](https://user-images.githubusercontent.com/62702170/100498170-a9046580-31a3-11eb-9729-58732daaf9ff.png)

なぜこのようことをするかというと
機種が変わると
safeAreaの外枠とパーツの距離は大きく変わります。
alighment constraitの参照先をsafeAreaの外枠に指定すると
大きく影響を受けてしまうからです
。

2020-12-07 06:24 UTC, your-chance commented
型くずれがなくきれいになったと思います。
commitメッセージで何を修正したか簡単に書けると良いと思います。

2020-12-08 13:20 UTC, mcz9mm requested changes
細かい箇所の修正ですがお願いします！

2020-12-08 13:20 UTC, mcz9mm commented on JyankenApp_iOS/JyankenApp/ViewController.swift
> +        func getImage() -> UIImage {
👍

2020-12-08 13:20 UTC, mcz9mm commented on JyankenApp_iOS/JyankenApp/ViewController.swift
> +        if( jankenPlayCheck == false ){
```
if( jankenPlayCheck == false ){
```

↓

```
if (jankenPlayCheck == false) {
```

2020-12-08 13:20 UTC, mcz9mm commented on JyankenApp_iOS/JyankenApp/ViewController.swift
> +        if( jankenPlayCheck == false ){
https://github.com/shinonome-inc/mobile_sakai/pull/10/files#diff-42d7e8375fc85e8a589de49053fac9686ba70c70cdc09a2f70be3a6c12d4ee5aR41

2020-12-08 13:20 UTC, mcz9mm commented on JyankenApp_iOS/JyankenApp/ViewController.swift
> +        if( jankenPlayCheck == false ){
https://github.com/shinonome-inc/mobile_sakai/pull/10/files#diff-42d7e8375fc85e8a589de49053fac9686ba70c70cdc09a2f70be3a6c12d4ee5aR41

2020-12-08 13:20 UTC, mcz9mm commented on JyankenApp_iOS/JyankenApp/ViewController.swift
> +    func timerStart(){
```
func timerStart(){
```
↓
```
func timerStart() {
```

2020-12-08 13:20 UTC, mcz9mm commented on JyankenApp_iOS/JyankenApp/ViewController.swift
> +        if ( timer != nil && count == 30 ) {
```
if (timer != nil && count == 30) {
```

2020-12-14 01:24 UTC, mcz9mm requested changes
まだ直っていない箇所があるのでそこ修正したらOKです

2020-12-14 01:24 UTC, mcz9mm commented on JyankenApp_iOS/JyankenApp/ViewController.swift
> +        if(jankenPlayCheck == false){
`if (jankenPlayCheck == false) {`

2020-12-14 01:24 UTC, mcz9mm commented on JyankenApp_iOS/JyankenApp/ViewController.swift
> +        if(jankenPlayCheck == false){
`if (jankenPlayCheck == false) {`

2020-12-14 08:40 UTC, mcz9mm commented on JyankenApp_iOS/JyankenApp/ViewController.swift
> +        if(jankenPlayCheck == false) {
`if (jankenPlayCheck == false) {`

2020-12-14 08:40 UTC, mcz9mm commented on JyankenApp_iOS/JyankenApp/ViewController.swift
> +        if(jankenPlayCheck == false) {
`if (jankenPlayCheck == false) {`

2020-12-14 08:40 UTC, mcz9mm commented on JyankenApp_iOS/JyankenApp/ViewController.swift
> +        if(jankenPlayCheck == false) {
`if (jankenPlayCheck == false) {`

2020-12-14 08:40 UTC, mcz9mm commented on JyankenApp_iOS/JyankenApp/ViewController.swift
> +        }else{
`} else {`

2020-12-14 08:40 UTC, mcz9mm commented on JyankenApp_iOS/JyankenApp/ViewController.swift
> +        if(jankenPlayCheck == false) {
これをみたらわかると思うけどif分の括弧の前後はスペースを入れましょう。
もしくは**全部入れないか**で統一しましょう。
混在しているのが良くないので
```
if (timer != nil && count == 30) {
```

2020-12-14 09:13 UTC, mcz9mm approved these changes
LGTM
![](https://media.giphy.com/media/VWUZa7JCe1XKo/giphy.gif)

2020-12-14 09:13 UTC, merged