模擬案件
shinonome-inc/mobile_sakai pull request #16
Opened 2021-05-22 11:32 UTC by yasyun

2021-05-22 23:41 UTC, ShuheiYoshidaJP commented
## お願い
1点目
OAuth以外にも実装されている部分が見受けられるので、
レビューして欲しい点を具体的に示してもらえますでしょうか
![イメージ](https://user-images.githubusercontent.com/62702170/119243510-5a5be500-bba2-11eb-89c0-0f47295b485e.png)

2点目
実装過程や参考にしたサイトなどを参照しながらレビューしたいので
issueなどに残してください。
起票されたissueは1点目と同じところに記載してください。

2021-05-27 08:37 UTC, ShuheiYoshidaJP reviewed
コメントしました。

2021-05-27 08:37 UTC, ShuheiYoshidaJP commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +            image = image?.scaleImage(scaleSize: 0.1)
イメージは絶対にnilにならない確信があるでしょうか？
絶対にnilにならないなら修正は不要です。

2021-05-27 08:37 UTC, ShuheiYoshidaJP commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +    }
最終的にはfigmaのデザインに忠実に実装してもらうことになると思われますが、
この関数たちはそれを考慮した結果、実装したものでしょうか？

2021-05-27 08:37 UTC, ShuheiYoshidaJP commented on Qiita_App/Qiita_App/QiitaQAuthPageViewController.swift
> +        if navigationAction.request.url?.scheme == "syunya-app", navigationAction.request.url?.host == "qiitasearch.com" {
``` swift
navigationAction.request.url?
```
nilの可能性は0でしょうか。
0でないなら修正する必要があります。

2021-05-27 08:37 UTC, ShuheiYoshidaJP commented on Qiita_App/Qiita_App/QiitaQAuthPageViewController.swift
> +        return url.queryItems?.first(where: { $0.name == param })?.value
nilの可能性は0でしょうか。
0でないなら修正する必要があります。

2021-05-27 08:37 UTC, ShuheiYoshidaJP commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +    }
このようなロジックは大事になってくるので
次回からはロジックの詳細などを細かくissueに記載するようにしてください。

2021-05-27 08:37 UTC, ShuheiYoshidaJP commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +    }
今回のプルリクのレビュー内容ではないですが、
ワードで記事検索できるAPIが用意されているので
そちらを利用してください。

2021-05-27 08:37 UTC, ShuheiYoshidaJP commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +    }
パッと見た感じではどのようなロジックになっているのか分からないので説明をお願いします。
今回のレビューの対象外でしたら、保留でOKです。

2021-05-27 10:31 UTC, mcz9mm commented on Qiita_App/Qiita_App/QiitaQAuthPageViewController.swift
> +        return url.queryItems?.first(where: { $0.name == param })?.value
ここの部分はreturnでStringのオプショナルを返すからそのままで良いと思うよ。
呼び出し側でnilチェックする感じ

2021-05-27 10:40 UTC, mcz9mm requested changes

2021-05-27 10:40 UTC, mcz9mm commented on Qiita_App/Qiita_App/QiitaQAuthPageViewController.swift
> +        if navigationAction.request.url?.scheme == "syunya-app", navigationAction.request.url?.host == "qiitasearch.com" {
ここもifで外れた部分の考慮って意味合いかな。

2021-05-27 10:40 UTC, mcz9mm commented on Qiita_App/Qiita_App/QiitaQAuthPageViewController.swift
> +                "client_id": "5703a0e3ecb356ae07cc2fec78aa8fe3262f28d9",
**重要**
Privateなリポジトリであってもアクセスキーに関してgit管理しないでください。
流出した際に悪用される危険性があります。
環境変数かgitignoreでgitの対象にならないようなクラスから呼び出すような実装にしてください。

2021-05-27 10:40 UTC, mcz9mm commented on Qiita_App/Qiita_App/QiitaQAuthPageViewController.swift
> +                "client_secret": "da41606a962f9e8b6b554359c3a9801c9cd0dd7c",
ここも同じく重要

2021-05-27 10:40 UTC, mcz9mm commented on Qiita_App/Qiita_App/QiitaQAuthPageViewController.swift
> +                    let result = String(data: response.value!!, encoding: .utf8)
ここのフォースアンラップ修正しましょう。

2021-05-27 10:40 UTC, mcz9mm commented on Qiita_App/Qiita_App/QiitaArticlePageViewController.swift
> +        let request = NSURLRequest(url: NSURL(string: articleUrl)! as URL)
`NSURL(string: articleUrl)!`
フォースアンラップ修正してください

2021-05-27 10:40 UTC, mcz9mm commented on Qiita_App/Qiita_App/QiitaQAuthPageViewController.swift
> +        let oauthURL = URL(string:"https://qiita.com/api/v2/oauth/authorize?client_id=5703a0e3ecb356ae07cc2fec78aa8fe3262f28d9&scope=readqiita&state=da41606a962f9e8b6b554359c3a9801c9cd0dd7c")!
**ここも重要**
https://github.com/shinonome-inc/mobile_sakai/pull/16/files/e91ae095831011fe867d357c2d2eafebb9cf0940#diff-9380f4d39da836b9b739976ba10372b3369a0d3330ed47eabf9c086c0fc740a0R50

2021-05-29 07:31 UTC, yasyun commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +    }
そうです、アイコンを表示するImageViewを丸くするのと、ユーザーのアイコンを取得してきた時に画像が大きすぎるので小さくしています。この辺りはまだこれから細かく調整していきたいので、ひとまずスルーでお願いします。

2021-05-29 07:55 UTC, yasyun commented on Qiita_App/Qiita_App/QiitaQAuthPageViewController.swift
> +        if navigationAction.request.url?.scheme == "syunya-app", navigationAction.request.url?.host == "qiitasearch.com" {
最初のif文の条件で同じところを参照していて、もしそこがnilになっていた場合はif文で弾かれるため問題ないのかと思っています。

2021-05-29 08:09 UTC, yasyun commented on Qiita_App/Qiita_App/QiitaQAuthPageViewController.swift
> +        if navigationAction.request.url?.scheme == "syunya-app", navigationAction.request.url?.host == "qiitasearch.com" {
個人的にはnilだった場合、その手前のif文の時点で弾かれるので問題ないかと思っているのですが、ifで外れた際に何か問題があるのでしょうか？

2021-05-29 08:10 UTC, yasyun commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +    }
承知しました、次回から注意します。すみませんでした。

2021-05-29 08:25 UTC, yasyun commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +    }
記事を取得してきたタイミングでタイトルだけをarticleTitlesに取り出していたのですが、実装していく中で重複して同じタイトルを取得していたことが発覚しました。なので、ここでforEachを使うことで記事のタイトルをそれぞれ全部と見比べて、同じタイトルが２回以上出てきたらその要素をarticleTitlesから削除しています。ひとまず今回のレビュー範囲からは少し外れているので花かと思います。

2021-05-29 08:27 UTC, yasyun commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +    }
この点はまた後日修正して、FeedPageのレビューをいただく時に見ていただこうと思います。ひとまずQiitaOAuthPageViewControllerの方をよろしくお願いいたします。

2021-05-29 08:55 UTC, yasyun commented on Qiita_App/Qiita_App/QiitaQAuthPageViewController.swift
> +                "client_id": "5703a0e3ecb356ae07cc2fec78aa8fe3262f28d9",
SecretKeysというクラスで管理するようにしました。

2021-05-29 11:15 UTC, ShuheiYoshidaJP commented on Qiita_App/Qiita_App/QiitaQAuthPageViewController.swift
> +        if navigationAction.request.url?.scheme == "syunya-app", navigationAction.request.url?.host == "qiitasearch.com" {
> nilの可能性は0でしょうか。
0でないなら修正する必要があります。

調べてみたらnilの可能性0ですね。
そのままでOKだと思います。
ifで外れたらログインできませんが、クラッシュはしないのでOKかなと思いました。

2021-05-29 11:20 UTC, ShuheiYoshidaJP commented
## お願い
SecretKey.swiftファイルをなんらかの形でレビュワーに渡せるような仕組みを作ってもらえるでしょうか。

2021-05-30 23:29 UTC, ShuheiYoshidaJP reviewed
コメントしました。

2021-05-30 23:29 UTC, ShuheiYoshidaJP commented on Qiita_App/Qiita_App/QiitaQAuthPageViewController.swift
> +    @IBOutlet var QiitaOAuthPage: WKWebView!
クラス内プロパティなので小文字スタートで！

2021-05-30 23:29 UTC, ShuheiYoshidaJP commented on Qiita_App/Qiita_App/QiitaQAuthPageViewController.swift
> +        QiitaOAuthPage.uiDelegate = self
WKUIDelegateについて調べました。
JSを制御するための宣言らしいですが
今後の実装でJSをwebview内で制御する実装をする予定でしょうか？

2021-05-31 06:43 UTC, mcz9mm commented
私にもください〜
> SecretKey.swiftファイルをなんらかの形でレビュワーに渡せるような仕組みを作ってもらえるでしょうか。

2021-05-31 06:57 UTC, mcz9mm requested changes

2021-05-31 06:57 UTC, mcz9mm commented on Qiita_App/Qiita_App/QiitaQAuthPageViewController.swift
> +            guard let code = QiitaOAuthPageViewController.getQueryStringParameter(url: (navigationAction.request.url?.absoluteString)!, param: "code") else { return }
`(url: (navigationAction.request.url?.absoluteString)!,`ここの部分もフォースアンラップ必要なんです。
guard letはカンマで分割できるので修正してみましょう。

```
 guard
    let url = navigationAction.request.url?.absoluteString,
    // 上で宣言したletが使える
    let code = QiitaOAuthPageViewController.getQueryStringParameter(url: url, param: "code") else { 
        return
}
```

2021-05-31 06:57 UTC, mcz9mm commented on Qiita_App/Qiita_App/QiitaArticlePageViewController.swift
> +        guard let unwrappedUrl = NSURL(string: articleUrl) else { return }
普通にURLで良いのでは？
```
guard let unwrappedUrl = URL(string: articleUrl) else { return }
let request = URLRequest(url: unwrappedUrl)
self.qiitaArticle.load(request)
```

2021-05-31 07:20 UTC, mcz9mm requested changes

2021-05-31 07:20 UTC, mcz9mm commented on Qiita_App/Qiita_App/DataModel.swift
> +        var profile_image_url: String
キャメルケースで扱おう。
ただ、jsonがこのようにスネークケースの場合はCodingKeysを使うと良いです。
https://qiita.com/_ha1f/items/bf1aad5ea3e927f59f9d#codingkeys

2021-05-31 07:20 UTC, mcz9mm commented on Qiita_App/Qiita_App/DataModel.swift
> +    var created_at: String
https://github.com/shinonome-inc/mobile_sakai/pull/16/files#diff-8a3c0a81a498bcb9282df35c10d8f596c3879d873db45b9bf9c9d0aa145561d5R21

2021-05-31 07:20 UTC, mcz9mm commented on Qiita_App/Qiita_App/DataModel.swift
> +    let rendered_body: String
https://github.com/shinonome-inc/mobile_sakai/pull/16/files#diff-8a3c0a81a498bcb9282df35c10d8f596c3879d873db45b9bf9c9d0aa145561d5R21

2021-05-31 07:20 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +    override func awakeFromNib() {
何も処理しないなら消しましょう

2021-05-31 07:20 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +            self.userIcon.image = image
self不要

2021-05-31 07:20 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +        self.articleTitle.text = data.title as String
self不要、as Stringも不要　（data.titleはStringなので）

2021-05-31 07:20 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +        self.userId.text = "@" + data.user.id as String
self不要、as Stringも不要　（data.user.idはStringなので）

2021-05-31 07:20 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +        self.postData.text = "投稿日：" + data.created_at as String
ここも

2021-05-31 07:20 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +        self.postData.text = "投稿日：" + data.created_at as String
Dateのフォーマットが違います
<img width="182" alt="スクリーンショット 2021-05-31 16 06 03" src="https://user-images.githubusercontent.com/11751495/120153803-1d3ec500-c22a-11eb-93a7-ba37a2be48ca.png">

LGTM数も必要かな
<img width="500" alt="スクリーンショット 2021-05-31 16 06 41" src="https://user-images.githubusercontent.com/11751495/120153881-33e51c00-c22a-11eb-89be-4bed78804046.png">

2021-05-31 07:20 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +    let trimImage = UIImage(cgImage: imgRef!, scale: image.scale, orientation: image.imageOrientation)
`imgRef!`フォースアンラップ

2021-05-31 07:20 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +extension UIImage {
このUIImageのExtensionは他のファイルからも利用できる全体的なスコープになっているので、ここのファイルに書くべきものではないです。
`UIImage+Extension.swift`みたいなファイルを作成してそちらに記述するようにしましょう。

2021-05-31 07:20 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +extension UIImageView {
これも同様。`UIImageView +Extension.swift`

2021-05-31 07:20 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +        if let text = searchBar.text {
ループとネストの複雑化はバグの温床になります。
今回の範囲でないのであれば別issueを作成してそちらに、今のロジックを記述したり
改善案を書いていきましょう。

2021-05-31 07:20 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +    }
同じくcellForRowAtの中のリファクタは必須かな。別issueで修正してください。
https://github.com/shinonome-inc/mobile_sakai/pull/16/files#diff-e0b9ab6547246d65d7cf411b168a0f75049d28dd25bfacc3b0bc39f25afc7984R138

2021-05-31 07:20 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +
これ繋がってるよね。改行消してください

2021-05-31 07:20 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +            QiitaArticlePageViewController  else { return }
`ler  else`→`ler else`

2021-05-31 07:20 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +            QiitaArticlePageViewController  else { return }
余計な空白が1つ分入ってる

2021-05-31 07:20 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +    }
レビューしてもらうとき差分でないはずだから気をつけてね。

2021-05-31 07:20 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +        return 50
別途
高さ固定ではないです。

2021-05-31 07:20 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +                print("Error: \(error)")
エラー時はエラー用画面表示
後で対応する必要がある箇所はコメント入れるとわかりやすいです。

// TODO: エラー表示する

2021-05-31 07:20 UTC, mcz9mm commented on Qiita_App/Qiita_App/TopPageViewController.swift
> +    override func viewDidLoad() {
何もしないなら消す

2021-05-31 07:20 UTC, mcz9mm commented on Qiita_App/Qiita_App/TopPageViewController.swift
> +
細かいけど不要な行なら消しましょう

2021-05-31 07:21 UTC, mcz9mm commented
別issueで対応する場合、差分がでないので今のうちに修正が必要な箇所は個人的にメモなどしておくようにしておいてください。

2021-06-03 06:21 UTC, yasyun commented on Qiita_App/Qiita_App/DataModel.swift
> +        var profile_image_url: String
先ほど調べてみたところ、現在ではSwiftでキャメルケース、JSONでスネークケースを使うときは、Swift4.1から使えるようになったkeyEncodingStrategyなどが用いれるとあったんですが、従来通りCodingKeysで実装した方がいいですか？

2021-06-03 06:25 UTC, mcz9mm commented on Qiita_App/Qiita_App/DataModel.swift
> +        var profile_image_url: String
`keyEncodingStrategy `で修正してみようか
任せるよ

2021-06-03 07:44 UTC, yasyun commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +        return 50
消し忘れてました、すみません。

2021-06-03 08:10 UTC, yasyun commented on Qiita_App/Qiita_App/QiitaQAuthPageViewController.swift
> +        QiitaOAuthPage.uiDelegate = self
僕が参考にしていた記事ではWKUIDelegateを使っていたのでそのように実装してしまったのですが、特に今後JSを使う予定もなく、削除しても今回の実装には影響がなかったので消しました。
あまり深い意味を調べずに実装してしまっていたので、これからはエラーが出なくても、実装に直接関係があるのかをきっちりチェックしていこうと思います。

2021-06-03 11:54 UTC, ShuheiYoshidaJP reviewed
LGTMです。

2021-06-03 11:54 UTC, ShuheiYoshidaJP commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +                jsonDecoder.keyDecodingStrategy = .convertFromSnakeCase
good

2021-06-04 02:09 UTC, mcz9mm commented on Qiita_App/Qiita_App/TopPageViewController.swift
> +
消したらコメントしてね。

2021-06-04 02:09 UTC, mcz9mm commented on Qiita_App/Qiita_App/TopPageViewController.swift
> +    override func viewDidLoad() {
消したらコメントしてね。

2021-06-04 02:22 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +extension UIImage {
修正お願いします

2021-06-04 02:22 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +extension UIImageView {
修正お願いします

2021-06-04 02:22 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +        let imageUrl = URL(string: data.user.profileImageUrl as String)
as String不要　（data.user.profileImageUrlはStringなので）

2021-06-04 02:22 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +            let imageData = try Data(contentsOf: imageUrl!)
フォースアンラップ

2021-06-04 02:22 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +        self.postData.text = "投稿日：" + data.createdAt as String
MUST：
ここもas Stringも不要

WANT：
あと、Dateのフォーマットが違うかな。
別対応ならToDoコメント入れてください

2021-06-04 02:22 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +
直したらコメント欲しいです

2021-06-04 02:22 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +            QiitaArticlePageViewController  else { return }
修正お願いします

2021-06-04 02:22 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +        if let text = searchBar.text {
issue作成したらこちらにそのリンクを貼ってください。

2021-06-04 02:22 UTC, mcz9mm commented on Qiita_App/Qiita_App/QiitaQAuthPageViewController.swift
> +            guard let code = QiitaOAuthPageViewController.getQueryStringParameter(url: (navigationAction.request.url?.absoluteString)!, param: "code") else { return }
修正したらコメントで教えてね

2021-06-04 02:23 UTC, mcz9mm commented on Qiita_App/Qiita_App/QiitaArticlePageViewController.swift
> +        guard let unwrappedUrl = NSURL(string: articleUrl) else { return }
どんな修正を行ったか返信してください

2021-06-04 02:25 UTC, mcz9mm requested changes
修正内容が多くて大変ですが、コメントした箇所に対応した旨を記載するようにして欲しいです。返信がないまま修正しているのはまだしも、何も修正していない状態も混じっているので、円滑にレビューが進められません。

2021-06-04 03:07 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +    }
issue化したらここにリンクを貼る

というところまでやろう👍

2021-06-04 03:08 UTC, mcz9mm commented on Qiita_App/Qiita_App/QiitaQAuthPageViewController.swift
> +        QiitaOAuthPage.uiDelegate = self
調べるの大事！

2021-06-05 07:41 UTC, yasyun commented on Qiita_App/Qiita_App/QiitaArticlePageViewController.swift
> +        guard let unwrappedUrl = NSURL(string: articleUrl) else { return }
コメントしていただいたように、NSURLからURLを使用するように変更し、わざわざ後からURLに変更しなくても良いようにしました。またNSURLRequestもURLRequestに変更しました。

2021-06-06 01:21 UTC, mcz9mm commented
各コメントの流れがわかりにくい場合はFiles Changedから該当箇所のコードを確認すると経緯がわかるかと思います。
<img width="1190" alt="スクリーンショット 2021-06-06 10 19 09" src="https://user-images.githubusercontent.com/11751495/120909502-b4839c80-c6b0-11eb-8e2e-780c7bba0843.png">
<img width="1146" alt="スクリーンショット 2021-06-06 10 19 19" src="https://user-images.githubusercontent.com/11751495/120909505-b77e8d00-c6b0-11eb-8bb0-6da13199e6ba.png">

2021-06-10 05:58 UTC, yasyun commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +            image = image?.scaleImage(scaleSize: 0.1)
修正しました。

2021-06-10 06:06 UTC, yasyun commented on Qiita_App/Qiita_App/QiitaQAuthPageViewController.swift
> +                "client_secret": "da41606a962f9e8b6b554359c3a9801c9cd0dd7c",
クラスSecretKeysに含めました。

2021-06-10 06:08 UTC, yasyun commented on Qiita_App/Qiita_App/QiitaQAuthPageViewController.swift
> +                    let result = String(data: response.value!!, encoding: .utf8)
修正しました。

2021-06-10 06:08 UTC, yasyun commented on Qiita_App/Qiita_App/QiitaArticlePageViewController.swift
> +        let request = NSURLRequest(url: NSURL(string: articleUrl)! as URL)
修正しました。

2021-06-10 06:11 UTC, yasyun commented on Qiita_App/Qiita_App/TopPageViewController.swift
> +    override func viewDidLoad() {
削除しました、事後報告になってしまいすみません。

2021-06-10 06:11 UTC, yasyun commented on Qiita_App/Qiita_App/TopPageViewController.swift
> +
こちらも同じく削除しました。

2021-06-10 06:21 UTC, yasyun commented on Qiita_App/Qiita_App/QiitaQAuthPageViewController.swift
> +        let oauthURL = URL(string:"https://qiita.com/api/v2/oauth/authorize?client_id=5703a0e3ecb356ae07cc2fec78aa8fe3262f28d9&scope=readqiita&state=da41606a962f9e8b6b554359c3a9801c9cd0dd7c")!
こちらもSecretKeysに含めました。

2021-06-10 06:23 UTC, yasyun commented on Qiita_App/Qiita_App/QiitaQAuthPageViewController.swift
> +    @IBOutlet var QiitaOAuthPage: WKWebView!
修正しました。

2021-06-10 06:26 UTC, yasyun commented on Qiita_App/Qiita_App/QiitaQAuthPageViewController.swift
> +            guard let code = QiitaOAuthPageViewController.getQueryStringParameter(url: (navigationAction.request.url?.absoluteString)!, param: "code") else { return }
修正しました。

2021-06-10 06:30 UTC, yasyun commented on Qiita_App/Qiita_App/DataModel.swift
> +        var profile_image_url: String
keyEncodingStrategyを使って修正しました。

2021-06-10 06:31 UTC, yasyun commented on Qiita_App/Qiita_App/DataModel.swift
> +    var created_at: String
keyEncodingStrategyで修正しました。

2021-06-10 06:37 UTC, yasyun commented on Qiita_App/Qiita_App/DataModel.swift
> +    let rendered_body: String
keyEncodingStrategyで修正しました。

2021-06-10 06:37 UTC, yasyun commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +    override func awakeFromNib() {
削除しました。

2021-06-10 06:37 UTC, yasyun commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +            self.userIcon.image = image
self削除しました。

2021-06-10 06:41 UTC, yasyun commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +                print("Error: \(error)")
後に修正が必要なところにはTODOでコメントを付けました。

2021-06-10 06:42 UTC, yasyun commented on Qiita_App/Qiita_App/TopPageViewController.swift
> +    override func viewDidLoad() {
削除しました。

2021-06-10 06:42 UTC, yasyun commented on Qiita_App/Qiita_App/TopPageViewController.swift
> +
削除しました。

2021-06-10 06:45 UTC, yasyun commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +        let imageUrl = URL(string: data.user.profileImageUrl as String)
as String削除しました。

2021-06-10 06:45 UTC, yasyun commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +            let imageData = try Data(contentsOf: imageUrl!)
修正しました。

2021-06-10 06:47 UTC, yasyun commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +        self.postData.text = "投稿日：" + data.createdAt as String
as String削除して、コメントでToDoを書きました。

2021-06-10 06:59 UTC, yasyun commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +        self.articleTitle.text = data.title as String
selfとas String削除しました。

2021-06-10 07:02 UTC, yasyun commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +        self.userId.text = "@" + data.user.id as String
同じくselfとas String削除しました。

2021-06-10 07:05 UTC, yasyun commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +        self.postData.text = "投稿日：" + data.created_at as String
selfとas String削除しました。
確か以前PGritでかいとさんが、「Contributionを返すAPIが既に廃止されていて、LGTM数はフォローフォロワーページで使用するAPIのレスポンスには含まれていない」みたいなことを質問していたと思うのですが、何処かからLGTM数を何とか算出して表示した方が良いのでしょうか？

2021-06-10 07:14 UTC, yasyun commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +    let trimImage = UIImage(cgImage: imgRef!, scale: image.scale, orientation: image.imageOrientation)
修正しました。

2021-06-10 07:23 UTC, yasyun commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +extension UIImage {
UIImage+Extension.swiftというファイルを作って、そちらに記述しました。

2021-06-10 07:23 UTC, yasyun commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +extension UIImageView {
同じくUIImageView+Extension.swiftというファイルを作って、そちらに記述しました。

2021-06-10 07:29 UTC, yasyun commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +
修正しました。

2021-06-10 07:29 UTC, yasyun commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +            QiitaArticlePageViewController  else { return }
修正しました。

2021-06-10 07:34 UTC, yasyun commented
先日、「修正内容のコメントが確認できないです」ということをPGritでお伝えした件なのですが、僕の方のGithubでコメントが多くなってきたことにより、自動的に途中のコメントがタブのようなものに隠れてしまっていたようで、気づけていませんでした。確認不足で申し訳ありませんでした。以後気をつけます。

2021-06-10 09:39 UTC, mcz9mm requested changes
PullRequestでさらに新しい別の内容を加えてしまうと永遠にPRがマージできないです。
コメントした箇所の内容をよく読んでどうするか決めていきましょう。

2021-06-10 09:39 UTC, mcz9mm commented on Qiita_App/Qiita_App/TagListCell.swift
> +class TagListCellViewController: UICollectionViewCell {
修正分の内容で新しくTagListCellViewControllerが追加されてるけど
このPRの対象外だと思います。

2021-06-10 09:39 UTC, mcz9mm commented on Qiita_App/Qiita_App/TagListCell.swift
> +class TagListCellViewController: UICollectionViewCell {
どうするか決めて対応していきましょう。
・このPRで再度ここの範囲をレビューし、修正する
・この修正分を取り消して別ブランチで作業をする

2021-06-10 09:39 UTC, mcz9mm commented on Qiita_App/Qiita_App/TagListPageViewController.swift
> +class TagListPageViewController: UIViewController {
ここも同じく新しく追加した分ですよね。
https://github.com/shinonome-inc/mobile_sakai/pull/16/commits/f7ea143e0e11ff82efdb0072ca3b0fe25ca82bfd#diff-66a2e33463e9e3021a01a0748e8b48df7b2645f058a2c184400feb2661a9de07R11

2021-06-10 09:39 UTC, mcz9mm commented on Qiita_App/Qiita_App/UIImage+Extension.swift
> +    func reSizeImage(reSize:CGSize)->UIImage {
細かいけど
`reSizeImage(reSize:CGSize)->UIImage`→`reSizeImage(reSize: CGSize)- > UIImage`

2021-06-10 09:39 UTC, mcz9mm commented on Qiita_App/Qiita_App/UIImage+Extension.swift
> +    func scaleImage(scaleSize:CGFloat)->UIImage {
`func scaleImage(scaleSize:CGFloat)->UIImage {`→`func scaleImage(scaleSize: CGFloat) -> UIImage {`

2021-06-10 09:39 UTC, mcz9mm commented on Qiita_App/Qiita_App/DataModel.swift
> +    var created_at: String
OK

2021-06-10 09:39 UTC, mcz9mm commented on Qiita_App/Qiita_App/DataModel.swift
> +        var profile_image_url: String
OK

2021-06-10 09:39 UTC, mcz9mm commented on Qiita_App/Qiita_App/QiitaArticlePageViewController.swift
> +        guard let unwrappedUrl = NSURL(string: articleUrl) else { return }
OK

2021-06-10 09:39 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +    override func awakeFromNib() {
OK

2021-06-10 09:39 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +            self.userIcon.image = image
OK

2021-06-10 09:40 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +        self.articleTitle.text = data.title as String
OK

2021-06-10 09:40 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +        self.userId.text = "@" + data.user.id as String
OK

2021-06-10 09:41 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +        self.postData.text = "投稿日：" + data.created_at as String
Kaito君に聞いて対応してみてください。

2021-06-10 09:41 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +    let trimImage = UIImage(cgImage: imgRef!, scale: image.scale, orientation: image.imageOrientation)
OK

2021-06-10 09:41 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +extension UIImage {
OK

2021-06-10 09:41 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +extension UIImageView {
OK

2021-06-10 09:41 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +
OK

2021-06-10 09:41 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +            QiitaArticlePageViewController  else { return }
OK

2021-06-10 09:41 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +        return 50
OK

2021-06-10 09:41 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +                print("Error: \(error)")
OK

2021-06-10 09:41 UTC, mcz9mm commented on Qiita_App/Qiita_App/TopPageViewController.swift
> +    override func viewDidLoad() {
OK

2021-06-10 09:41 UTC, mcz9mm commented on Qiita_App/Qiita_App/TopPageViewController.swift
> +
OK

2021-06-10 09:42 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +        let imageUrl = URL(string: data.user.profileImageUrl as String)
OK

2021-06-10 09:42 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +            let imageData = try Data(contentsOf: imageUrl!)
OK

2021-06-10 09:42 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +        self.postData.text = "投稿日：" + data.createdAt as String
OK

2021-06-12 07:57 UTC, yasyun commented on Qiita_App/Qiita_App/TagListCell.swift
> +class TagListCellViewController: UICollectionViewCell {
すみません、模擬案件を進めていく上でのプルリクの出し方をきちんと理解できていなかったです。
もう既にそこそこ実装を進めてしまったため、差分を消してしまうと結構苦しいところがあるので、申し訳ないのですがここの範囲のレビューもお願いしてもよろしいでしょうか、申し訳ありません。
このプルリクを出してからレビューをいただくまでの間に、同じくブランチを切らずに追加で実装をしてしまったので、申し訳ないのですがその部分についても、レビューをいただく形でも大丈夫でしょうか？

2021-06-12 07:58 UTC, yasyun commented on Qiita_App/Qiita_App/TagListPageViewController.swift
> +class TagListPageViewController: UIViewController {
はい、そうです。

2021-06-14 02:34 UTC, mcz9mm commented on Qiita_App/Qiita_App/TagListCell.swift
> +class TagListCellViewController: UICollectionViewCell {
このPRがマージされたらその作業しているbranchで最新のmain branchを取り込むようにしてみましょう。
> このプルリクを出してからレビューをいただくまでの間に、同じくブランチを切らずに追加で実装をしてしまったので、申し訳ないのですがその部分についても、レビューをいただく形でも大丈夫でしょうか？

2021-06-14 02:42 UTC, mcz9mm requested changes

2021-06-14 02:42 UTC, mcz9mm commented on Qiita_App/Qiita_App/TagListPageViewController.swift
> +        self.request()
self不要

2021-06-14 02:42 UTC, mcz9mm commented on Qiita_App/Qiita_App/TagListPageViewController.swift
> +                //let jsonDecoder = JSONDecoder()
不要なら消しましょう

2021-06-14 02:42 UTC, mcz9mm commented on Qiita_App/Qiita_App/TagListCell.swift
> +        self.tagName.text = data.id
self不要です
他も一緒

2021-06-17 06:23 UTC, yasyun commented on Qiita_App/Qiita_App/UIImage+Extension.swift
> +    func reSizeImage(reSize:CGSize)->UIImage {
-と>の間にスペースを入れるとエラーが出てしまうんですが、修正した方が良いのでしょうか？

2021-06-17 06:26 UTC, yasyun commented on Qiita_App/Qiita_App/TagListPageViewController.swift
> +                //let jsonDecoder = JSONDecoder()
ここは不要な部分ではなく、後からDataModelと同じくスネークケースに変更するため、一時的にコメントアウトしています。
ここについては別ブランチで変更します。

2021-06-17 06:47 UTC, yasyun commented on Qiita_App/Qiita_App/TagListPageViewController.swift
> +        self.request()
修正しました。

2021-06-17 06:47 UTC, yasyun commented on Qiita_App/Qiita_App/TagListCell.swift
> +        self.tagName.text = data.id
修正しました。

2021-06-17 06:58 UTC, yasyun commented on Qiita_App/Qiita_App/UIImage+Extension.swift
> +    func scaleImage(scaleSize:CGFloat)->UIImage {
修正しました。

2021-06-17 06:58 UTC, yasyun commented on Qiita_App/Qiita_App/UIImage+Extension.swift
> +    func reSizeImage(reSize:CGSize)->UIImage {
修正しました。

2021-06-17 07:14 UTC, mcz9mm commented on Qiita_App/Qiita_App/UIImage+Extension.swift
> +    func reSizeImage(reSize:CGSize)->UIImage {
コロンの後にもスペースを入れてください

2021-06-17 07:15 UTC, mcz9mm commented on Qiita_App/Qiita_App/UIImage+Extension.swift
> +    func scaleImage(scaleSize:CGFloat)->UIImage {
コロンの後にもスペースを入れてください

2021-06-17 07:15 UTC, mcz9mm commented
2点修正したらOKです。

2021-06-17 07:18 UTC, yasyun commented on Qiita_App/Qiita_App/UIImage+Extension.swift
> +    func reSizeImage(reSize:CGSize)->UIImage {
すみません、見逃していました。修正しました。

2021-06-17 07:18 UTC, yasyun commented on Qiita_App/Qiita_App/UIImage+Extension.swift
> +    func scaleImage(scaleSize:CGFloat)->UIImage {
修正しました。

2021-06-17 07:43 UTC, merged

2021-06-17 09:25 UTC, yasyun commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +    }
ページネーションのロジック記載先issue
[https://github.com/shinonome-inc/mobile_sakai/issues/18](#2 )

2021-06-19 10:38 UTC, yasyun commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +    }
こちらのArticleTitlesに関しては、SearchBarの記事検索のロジックを変更したことに伴い必要なくなったので、このリファクタのコード自体をまるまる削除しました。

2021-06-19 10:41 UTC, yasyun commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +    }
対応issue [#2](https://github.com/shinonome-inc/mobile_sakai/issues/18)

2021-06-24 06:39 UTC, yasyun commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +    }
記事検索できるAPIに変更
issue: [#2](https://github.com/shinonome-inc/mobile_sakai/issues/18)

2021-06-24 10:17 UTC, yasyun commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +        self.postData.text = "投稿日：" + data.created_at as String
Kaitoさんの件はフォローフォロワーページでのことだったみたいなので、今回とは別件のようです。
なので自分で調べてみたところ、ここのFeedPageで使用しているAPIである、/api/v2/itemsのレスポンスにはLGTM数は含められておらず、/api/v2/authenticated_user/itemsのレスポンスのlike_countしか確認できませんでした。
その場合、FeedPageCellでもう一度別のリクエストを行い、全く別のレスポンスを取得する必要があるのですが、どうすればよいでしょうか？

2021-06-25 09:53 UTC, yasyun commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +        if let text = searchBar.text {
変更先issue:[#2](https://github.com/shinonome-inc/mobile_sakai/issues/18)