模擬案件_#2_addFeedPage
shinonome-inc/mobile_sakai pull request #19
Opened 2021-06-25 12:26 UTC by yasyun

2021-06-28 03:19 UTC, mcz9mm requested changes

2021-06-28 03:19 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +    func setArticleCell(date: DataItem) {
タイポ　date

2021-06-28 03:19 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +            if image.size.height > 300 && image.size.width > 300 {
ここでやってることの目的って何ですか？
28~41行目の範囲で

2021-06-28 03:19 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +        articleInfo.text = "@" + date.user.id + " 投稿日：" + dateFormat.string(from: formattedDate) + " LGTM：" + String(date.likesCount)
個人的にはString()で文字にするより`""`に変数入れる方が好みかな。
"@\(date.user.id) 投稿日:\(dateFormat.string(from: formattedDate)) LGTM: \(date.likesCount)"

2021-06-28 03:19 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +func StringToDate(dateValue: String, format: String) -> Date {
他のクラスや画面で使わないんだったらここのファイルでも良いけど、使い回す想定があるなら
共通化できるようにしたい

2021-06-28 03:19 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +        let dateFormat = DateFormatter()
これも使いまわせるようにしたいね

2021-06-28 03:19 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +                self.articles.forEach() { nowArticle in
リファクタ：
ここのロジックが分からないのでやっていることを整理してみて

2021-06-28 03:22 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +            if image.size.height > 300 && image.size.width > 300 {
他のメンバーに聞いたりしてね。多分このような実装はやってないはず

2021-07-01 08:54 UTC, yasyun commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +        let dateFormat = DateFormatter()
新しくDataFormat.swiftを作り、関数にしてそちらに移動させました。

2021-07-01 08:58 UTC, yasyun commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +func StringToDate(dateValue: String, format: String) -> Date {
新しくDataFormat.swiftを作り、関数にしてそちらに移動させました。
今のところDataFormat.swiftにそのまま関数を定義しているのですが、クラスを作ってその中で定義した方がよいでしょうか？

2021-07-01 09:01 UTC, yasyun commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +                self.articles.forEach() { nowArticle in
一応、issue[#2](https://github.com/shinonome-inc/mobile_sakai/issues/18)の方にロジックは記載してあるのですが、そちらをご覧いただけましたでしょうか？

2021-07-01 09:02 UTC, yasyun commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +        articleInfo.text = "@" + date.user.id + " 投稿日：" + dateFormat.string(from: formattedDate) + " LGTM：" + String(date.likesCount)
修正しました。

2021-07-01 09:02 UTC, yasyun commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +    func setArticleCell(date: DataItem) {
修正しました。

2021-07-01 09:43 UTC, yasyun commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +            if image.size.height > 300 && image.size.width > 300 {
ImageViewに画像を当てはめてから、clipToBoundなどを使用してユーザーアイコンを丸く表示していたため、それに伴うUI調整のために、画像サイズの変更や画像の切り取りをしていました。
しかしkaitoさんにお聞きしたところ、画像自体の大きさは変更していないということだったので、最初から画像を丸く切り取り、それをImageViewに当てはめるように変更しました。
結果、以前よりも綺麗にアイコンを表示することができるようになりました。

2021-07-01 09:45 UTC, yasyun commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +            if image.size.height > 300 && image.size.width > 300 {
この変更による差分
- UIImage+Extension.swiftの中身を変更
- UIImageView+Extension.swift　⇒　EnhancedCircleImageView.swiftに名前を変更
- EnhancedCircleImageView.swiftの中身を変更

2021-07-01 10:18 UTC, mcz9mm commented
ブランチ名がちょっと雑かな。
developやfeatureを手前につけて、issue番号を振ってあげると管理しやすいと思う。
https://qiita.com/c6tower/items/fe2aa4ecb78bef69928f

develop/#2
feature/#2

2021-07-01 10:19 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +                self.articles.forEach() { nowArticle in
> リファクタリング (refactoring) とは、コンピュータプログラミングにおいて、プログラムの外部から見た動作を変えずにソースコードの内部構造を整理することである。

2021-07-01 10:21 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +                self.articles.forEach() { nowArticle in
とってきたデータをそのままtableviewで表示するのはダメなの？

> 記事のリファクタロジック
forEachでarticlesの中身を順番に取り出す
for in enumeratedで、forEachにより取り出されている記事と、全ての記事のタイトルを見比べる
overlapping(重複数)が2つ以上になったら、index(現在の配列インデックス)の記事を、articlesから削除する

2021-07-01 10:22 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +func StringToDate(dateValue: String, format: String) -> Date {
その方がいいね

2021-07-01 10:41 UTC, mcz9mm requested changes

2021-07-01 10:41 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +                article.title.lowercased().contains(text.lowercased())
記事検索の意味が違うね。これは取得した記事のフィルター(絞り込み)になってると思うよ。
APIを使ってワード検索した結果を取得できるようにしてください。

https://github.com/shinonome-inc/mobile_sakai/issues/18#issuecomment-867381119

2021-07-01 10:43 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +                self.articles.forEach() { nowArticle in
データが重複して取得されてしまうなら根本的にそれを修正しないといけないと思う。

2021-07-02 03:11 UTC, ShuheiYoshidaJP reviewed
その1
コメントしました。

2021-07-02 03:11 UTC, ShuheiYoshidaJP commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +                        }
重複を排除する目的がわかりませんが、
厳密に行いたいならタイトルより
記事が一意に決まる"id"を使用した方がいいと思います。
<img width="446" alt=" 2021-07-02 12 04 03" src="https://user-images.githubusercontent.com/62702170/124214705-9da85c80-db2d-11eb-92ec-be3068dcdad9.png">

2021-07-02 03:13 UTC, ShuheiYoshidaJP commented
その2
コメントしました。
SearchBarとTableViewの間に空いているスペースが気になります。
![イメージ](https://user-images.githubusercontent.com/62702170/124215375-d5fc6a80-db2e-11eb-90fc-1bbbe0e95c0a.png)

2021-07-08 06:40 UTC, yasyun commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +func StringToDate(dateValue: String, format: String) -> Date {
SetDataFormatクラスの中に定義するように修正しました。

2021-07-08 06:43 UTC, yasyun commented
> その2
> コメントしました。
> SearchBarとTableViewの間に空いているスペースが気になります。
> ![イメージ](https://user-images.githubusercontent.com/62702170/124215375-d5fc6a80-db2e-11eb-90fc-1bbbe0e95c0a.png)

スペースを埋めるように修正しました。

2021-07-08 06:50 UTC, yasyun commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +                self.articles.forEach() { nowArticle in
以前レビューをいただいた際に、cellForRowAtの中のリファクタが必要ということが書いてあったので、その中身はここで言うarticlesなのかと思い、特に今まで重複して表示された事はなかったのですが、この部分を実装しました。
取ってきたデータをそのまま表示していても今まで特に問題はなかったので、この部分は削除しようと思います。

2021-07-08 06:51 UTC, yasyun commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +                        }
ありがとうございます。この部分の仕組みは削除することになったので、今回いただいたアドバイスは次回以降に活かしたいと思います。

2021-07-08 07:37 UTC, yasyun commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +                article.title.lowercased().contains(text.lowercased())
QiitaAPIのクエリパラメータへSearchBarに入力された文字をくっつけて、titleに検索した文字列が含まれている記事のみを取得してくるように変更しました。
意味合いとしてはこの修正で合っていますでしょうか？

2021-07-08 07:59 UTC, yasyun commented
ページネーションの仕組みについては変更した方が良いのでしょうか？

2021-07-08 08:37 UTC, yasyun commented
ローカルのブランチ名は変更したのですが、リモートのブランチ名はひとまず次回以降から準拠させる形で大丈夫でしょうか？

2021-07-08 08:53 UTC, yasyun commented
> ブランチ名がちょっと雑かな。
> developやfeatureを手前につけて、issue番号を振ってあげると管理しやすいと思う。
> https://qiita.com/c6tower/items/fe2aa4ecb78bef69928f
> 
> develop/#2
> feature/#2

ローカルのブランチ名は変更したのですが、リモートのブランチ名はひとまず次回以降から準拠させる形で大丈夫でしょうか？

2021-07-09 01:23 UTC, mcz9mm commented
AutoLayoutの制約が壊れてるログが出てるね
```
2021-07-09 10:22:11.551571+0900 Qiita_App[98897:2480547] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x6000000a7610 Qiita_App.EnhancedCircleImageView:0x7fa2af608b30.height == 50   (active)>",
    "<NSLayoutConstraint:0x6000000a7a20 UITableViewCellContentView:0x7fa2af618370.bottomMargin == Qiita_App.EnhancedCircleImageView:0x7fa2af608b30.bottom + 6   (active)>",
    "<NSLayoutConstraint:0x6000000a7a70 Qiita_App.EnhancedCircleImageView:0x7fa2af608b30.top == UITableViewCellContentView:0x7fa2af618370.topMargin   (active)>",
    "<NSLayoutConstraint:0x6000000a7de0 'UIView-bottomMargin-guide-constraint' V:[UILayoutGuide:0x600001a890a0'UIViewLayoutMarginsGuide']-(11)-|   (active, names: '|':UITableViewCellContentView:0x7fa2af618370 )>",
    "<NSLayoutConstraint:0x6000000e6670 'UIView-Encapsulated-Layout-Height' UITableViewCellContentView:0x7fa2af618370.height == 78.3333   (active)>",
    "<NSLayoutConstraint:0x6000000a7d40 'UIView-topMargin-guide-constraint' V:|-(11)-[UILayoutGuide:0x600001a890a0'UIViewLayoutMarginsGuide']   (active, names: '|':UITableViewCellContentView:0x7fa2af618370 )>"
)
```

2021-07-09 01:28 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +        articles.removeAll()
スクロール中に検索バーで検索したりすると確定でクラッシュするから修正して欲しいです。

2021-07-09 01:28 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +                self.articles.forEach() { nowArticle in
はい

2021-07-09 01:28 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +                article.title.lowercased().contains(text.lowercased())
それでいいと思うよ

2021-07-09 01:33 UTC, mcz9mm reviewed
今の状態だとかなりスクロールがカクついてるので改善しないといけないかもね。
> ページネーションの仕組みについては変更した方が良いのでしょうか？

![Jul-09-2021 10-30-38](https://user-images.githubusercontent.com/11751495/125010048-bb7f3f80-e0a0-11eb-9ec6-b32e86455d74.gif)

2021-07-09 01:34 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +        articles.removeAll()
tableviewの
`cell.setArticleCell(data: articles[indexPath.row])`の部分で検索と同時に`articles.removeAll()`してるせいかな、

2021-07-09 01:39 UTC, mcz9mm commented
次からマストでお願いします
> ローカルのブランチ名は変更したのですが、リモートのブランチ名はひとまず次回以降から準拠させる形で大丈夫でしょうか？

2021-07-15 08:53 UTC, yasyun commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +        articles.removeAll()
> AutoLayoutの制約が壊れてるログが出てるね
> 
> ```
> 2021-07-09 10:22:11.551571+0900 Qiita_App[98897:2480547] [LayoutConstraints] Unable to simultaneously satisfy constraints.
> 	Probably at least one of the constraints in the following list is one you don't want. 
> 	Try this: 
> 		(1) look at each constraint and try to figure out which you don't expect; 
> 		(2) find the code that added the unwanted constraint or constraints and fix it. 
> (
>     "<NSLayoutConstraint:0x6000000a7610 Qiita_App.EnhancedCircleImageView:0x7fa2af608b30.height == 50   (active)>",
>     "<NSLayoutConstraint:0x6000000a7a20 UITableViewCellContentView:0x7fa2af618370.bottomMargin == Qiita_App.EnhancedCircleImageView:0x7fa2af608b30.bottom + 6   (active)>",
>     "<NSLayoutConstraint:0x6000000a7a70 Qiita_App.EnhancedCircleImageView:0x7fa2af608b30.top == UITableViewCellContentView:0x7fa2af618370.topMargin   (active)>",
>     "<NSLayoutConstraint:0x6000000a7de0 'UIView-bottomMargin-guide-constraint' V:[UILayoutGuide:0x600001a890a0'UIViewLayoutMarginsGuide']-(11)-|   (active, names: '|':UITableViewCellContentView:0x7fa2af618370 )>",
>     "<NSLayoutConstraint:0x6000000e6670 'UIView-Encapsulated-Layout-Height' UITableViewCellContentView:0x7fa2af618370.height == 78.3333   (active)>",
>     "<NSLayoutConstraint:0x6000000a7d40 'UIView-topMargin-guide-constraint' V:|-(11)-[UILayoutGuide:0x600001a890a0'UIViewLayoutMarginsGuide']   (active, names: '|':UITableViewCellContentView:0x7fa2af618370 )>"
> )
> ```

修正しました。

2021-07-15 08:53 UTC, yasyun commented
> AutoLayoutの制約が壊れてるログが出てるね
> 
> ```
> 2021-07-09 10:22:11.551571+0900 Qiita_App[98897:2480547] [LayoutConstraints] Unable to simultaneously satisfy constraints.
> 	Probably at least one of the constraints in the following list is one you don't want. 
> 	Try this: 
> 		(1) look at each constraint and try to figure out which you don't expect; 
> 		(2) find the code that added the unwanted constraint or constraints and fix it. 
> (
>     "<NSLayoutConstraint:0x6000000a7610 Qiita_App.EnhancedCircleImageView:0x7fa2af608b30.height == 50   (active)>",
>     "<NSLayoutConstraint:0x6000000a7a20 UITableViewCellContentView:0x7fa2af618370.bottomMargin == Qiita_App.EnhancedCircleImageView:0x7fa2af608b30.bottom + 6   (active)>",
>     "<NSLayoutConstraint:0x6000000a7a70 Qiita_App.EnhancedCircleImageView:0x7fa2af608b30.top == UITableViewCellContentView:0x7fa2af618370.topMargin   (active)>",
>     "<NSLayoutConstraint:0x6000000a7de0 'UIView-bottomMargin-guide-constraint' V:[UILayoutGuide:0x600001a890a0'UIViewLayoutMarginsGuide']-(11)-|   (active, names: '|':UITableViewCellContentView:0x7fa2af618370 )>",
>     "<NSLayoutConstraint:0x6000000e6670 'UIView-Encapsulated-Layout-Height' UITableViewCellContentView:0x7fa2af618370.height == 78.3333   (active)>",
>     "<NSLayoutConstraint:0x6000000a7d40 'UIView-topMargin-guide-constraint' V:|-(11)-[UILayoutGuide:0x600001a890a0'UIViewLayoutMarginsGuide']   (active, names: '|':UITableViewCellContentView:0x7fa2af618370 )>"
> )
> ```

修正しました。

2021-07-15 08:55 UTC, yasyun commented
> 今の状態だとかなりスクロールがカクついてるので改善しないといけないかもね。
> 
> > ページネーションの仕組みについては変更した方が良いのでしょうか？
> 
> ![Jul-09-2021 10-30-38](https://user-images.githubusercontent.com/11751495/125010048-bb7f3f80-e0a0-11eb-9ec6-b32e86455d74.gif)

画像のキャッシュ化をしたところ、ページネーションの仕組みは変えていないのですが、かなりスムーズに動くようになりました。
しばらく上下に動かしてましたが、ガクガクする事はなくなりました。
一応これで改善したように思えるのですが、ページネーションの仕組みも変更した方がよいでしょうか？

2021-07-15 09:02 UTC, yasyun commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +        articles.removeAll()
request()の中で、removeFlagがtrueの時にremoveAllするように変更しました。
removeFlagを立てた理由は、そのままrequest()の中にremoveAllを入れてしまうと、ページネーションができなくなってしまうためです。

2021-07-15 10:03 UTC, yasyun commented
なぜか同じpushが２回されていることになってしまいました。すみません。

2021-07-15 10:57 UTC, mcz9mm requested changes
細かいですがエラー時もしっかり考慮しましょう
画像データが取れない場合、デフォルトの画像を用意してあげるなど工夫してみましょう

2021-07-15 10:57 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +        if text == "" {
もっとシンプルに書けるよ

`removeFlag = text == ""`

2021-07-15 10:57 UTC, mcz9mm commented on Qiita_App/Qiita_App/UIImage+Extension.swift
> +                // error handling
エラーの場合は考慮しない？

2021-07-15 10:57 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +                if self.removeFlag == true {
bool値の場合は`==`でチェックする必要ないよ
`if self.removeFlag {` 仮にfalseをチェックしたいなら`if !self.removeFlag {`

2021-07-15 10:57 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +                    print("error")
エラーの場合は考慮しない？

2021-07-15 11:04 UTC, mcz9mm commented
定例でも伝えたけど画像読み込みでメインスレッドを遮っているせいでカクつきが発生してたと思うよ。
ページネーションは一旦このままで良いです。

> 画像のキャッシュ化をしたところ、ページネーションの仕組みは変えていないのですが、かなりスムーズに動くようになりました。
しばらく上下に動かしてましたが、ガクガクする事はなくなりました。
一応これで改善したように思えるのですが、ページネーションの仕組みも変更した方がよいでしょうか？

2021-07-15 11:09 UTC, mcz9mm commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +        articles.removeAll()
今軽く触ったけど検索中にスクロールするとたまに落ちるから潜在的なバグは取り除けてないと思うよ。
一旦ここは今回のPRでは対象外にするので別途issueを作成して調査してみてください。

2021-07-27 05:48 UTC, yasyun commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +        if text == "" {
修正しました。

2021-07-27 06:23 UTC, yasyun commented on Qiita_App/Qiita_App/UIImage+Extension.swift
> +                // error handling
仕組みを変更したことでここの部分は削除しました。

2021-07-27 06:53 UTC, yasyun commented on Qiita_App/Qiita_App/FeedPageCell.swift
> +                    print("error")
エラーの場合は`errorUserIcon`という専用のアイコンを表示するように変更しました。

2021-07-27 06:54 UTC, yasyun commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +                if self.removeFlag == true {
bool値をあまり使い慣れていなかったので抜けていました、ありがとうございます。
修正しました。

2021-07-27 07:36 UTC, yasyun commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +        articles.removeAll()
issueを立てたらここにリンクを貼るようにします。

2021-07-27 08:02 UTC, mcz9mm commented
LGTM

2021-07-27 08:02 UTC, merged

2021-08-18 11:24 UTC, yasyun commented on Qiita_App/Qiita_App/FeedPageViewController.swift
> +        articles.removeAll()
issueを立てました。　issue:[SearchBarクラッシュエラー](https://github.com/shinonome-inc/mobile_sakai/issues/24)