模擬案件_#3_addTagPage
shinonome-inc/mobile_sakai pull request #21
Opened 2021-07-29 11:17 UTC by yasyun

2021-07-29 21:14 UTC, ShuheiYoshidaJP reviewed
コメントしました。

2021-07-29 21:14 UTC, ShuheiYoshidaJP commented on Qiita_App/Qiita_App/TagListCell.swift
> +        guard let imageUrl = URL(string: data.iconUrl) else { return }
仮にこの部分でnilチェックで引っかかると
``` swift
tagName.text = data.id
tagCount.text = "記事件数：" + String(data.itemsCount)
tagfollowers.text = "フォロワー数：" + String(data.followersCount)
```
この処理が行われずに
返されてしまうので
nilチェックして画像をセットするのはsetTagCellメソッド内で
一番最後に行った方がいいと思われます。

2021-07-29 21:16 UTC, ShuheiYoshidaJP commented
<img width="659" alt=" 2021-07-30 6 15 47" src="https://user-images.githubusercontent.com/62702170/127566929-a22e602c-2f4f-459a-a856-6ec1d4d271d1.png">
TagDetailですが
モーダル以外にも違う点がありそうです。

2021-07-29 21:26 UTC, ShuheiYoshidaJP commented
issueを拝見しましたが、

> 4. 制約修正により崩れなくなった　→　しかしセルの中で制約が壊れてしまった。いろいろ試しましたが改善できなかったので、アドバイスをいただきたいです。

どのような修正行ったのか？
何を試したのか？
をissueにのせて欲しかったです。

あと
https://youtu.be/hZwQBF8gUmQ
↑こちらを見ましたか？
わかりづらい点あったら教えてください。

2021-08-05 05:04 UTC, yasyun commented
> issueを拝見しましたが、
> 
> > 1. 制約修正により崩れなくなった　→　しかしセルの中で制約が壊れてしまった。いろいろ試しましたが改善できなかったので、アドバイスをいただきたいです。
> 
> どのような修正行ったのか？
> 何を試したのか？
> をissueにのせて欲しかったです。
> 
> あと
> https://youtu.be/hZwQBF8gUmQ
> ↑こちらを見ましたか？
> わかりづらい点あったら教えてください。

issueの方にこれまでの修正履歴を覚えている限りですが記載しました。
shuさんの解説動画は拝見しました。動画の内容はとても分かりやすかったと思います、ありがとうございます。
動画内容を試した上でうまくいかず、Pull Requestを出したのですが、改善案を思いついたので少しそちらを試してみようと思います。
その上で動画の内容について疑問点があれば、折り返し質問させていただこうと思います。よろしくお願いします。

2021-08-05 05:22 UTC, yasyun commented on Qiita_App/Qiita_App/TagListCell.swift
> +        guard let imageUrl = URL(string: data.iconUrl) else { return }
一番最後に行うように修正しました。

2021-08-05 07:33 UTC, yasyun commented
制約の問題は解決できました。ありがとうございました。

2021-08-05 07:51 UTC, yasyun commented
タグ画面のアイコンがキャッシュ化できていないので、次回にその点も併せて修正します。

2021-08-05 08:28 UTC, ShuheiYoshidaJP reviewed
コメントしました。
今回はペンディングでいいかと思われます。

2021-08-05 08:28 UTC, ShuheiYoshidaJP commented on Qiita_App/Qiita_App/setTagDetailCell.swift
> +
DateFormatterに関しては他の部分でも使うと思われるので
共通化してみたいですねー

2021-08-08 08:44 UTC, yasyun commented on Qiita_App/Qiita_App/setTagDetailCell.swift
> +
一応DataFormat.swiftのファイルにメソッドを記述して共通化しているつもりなのですが、もう少し汎用性を抑えて簡潔に使用できるようにした方が良いですか？

2021-08-08 09:11 UTC, ShuheiYoshidaJP commented on Qiita_App/Qiita_App/setTagDetailCell.swift
> +
例ですが
APIのデータを受け取り、メソッド内でDate型に変換して、日本語表記のテキストに変換できると
setArticleCellメソッド内がかなりスッキリすると思います。
↓declare
``` swift
class CustomDateFormatter {
    func fromDateStringToJpDateString(date: String) -> String {} //Qiita APIの日付データから日本語表記の日付へ変換
}
```
↓use
``` swift
var formatter = CustomDateFormatter()
articleTitle.text = formatter.fromDateStringToJpDateString(date: data.createdAt)
```

2021-08-08 10:33 UTC, yasyun commented on Qiita_App/Qiita_App/setTagDetailCell.swift
> +
例に挙げていただいたような形で修正しました。

2021-08-08 10:35 UTC, yasyun commented
dateFormatメソッドを修正したことで、FeedPageのセルにおける表示の部分のコードにも差分が出ています。また、タグ画面のアイコンもキャッシュ化しました。

2021-08-09 02:23 UTC, ShuheiYoshidaJP commented
<img width="450" alt="イメージ" src="https://user-images.githubusercontent.com/62702170/128654451-c167e66d-8f86-4224-a00d-647b8c7a27b7.png">
赤枠内のスペースが気になりました。
別のブランチで修正予定でしたら、保留で構いません。
LGTMです。

2021-08-16 00:54 UTC, mcz9mm requested changes
コメントしましたので確認お願いします。

画像のキャッシュ化対策は早めにやっておいたほうが良いと思います
(別issue)

あと、iPhone12 pro maxでビルドするとレイアウト描画おかしいのでチェックしておいてください。
![Aug-16-2021 09-44-53](https://user-images.githubusercontent.com/11751495/129498211-c6fca48d-585f-40bd-b8a9-cbdae7202a8d.gif)

2021-08-16 00:54 UTC, mcz9mm commented on Qiita_App/Qiita_App/TagDetailPageViewController.swift
> +    var url = "https://qiita.com/api/v2/items?count=20"
基本let、変更するものだけvarを使うようにしましょう

2021-08-16 00:54 UTC, mcz9mm commented on Qiita_App/Qiita_App/TagDetailPageViewController.swift
> +        AF.request(
todoコメント追加しておいてください。
Alamofire部分共通化

2021-08-16 00:54 UTC, mcz9mm commented on Qiita_App/Qiita_App/TagListPageViewController.swift
> +    var url = "https://qiita.com/api/v2/tags?sort=count&page="
ここもlet

2021-08-16 00:54 UTC, mcz9mm commented on Qiita_App/Qiita_App/TagListPageViewController.swift
> +        cell.contentView.layer.borderColor = UIColor.gray.cgColor
Q: Figmaのカラーと一致していますか？

2021-08-18 09:03 UTC, yasyun commented on Qiita_App/Qiita_App/TagDetailPageViewController.swift
> +        AF.request(
追加しました。

2021-08-18 09:03 UTC, yasyun commented on Qiita_App/Qiita_App/TagDetailPageViewController.swift
> +    var url = "https://qiita.com/api/v2/items?count=20"
修正しました。

2021-08-18 09:05 UTC, yasyun commented on Qiita_App/Qiita_App/TagListPageViewController.swift
> +    var url = "https://qiita.com/api/v2/tags?sort=count&page="
修正しました。

2021-08-18 09:39 UTC, yasyun commented on Qiita_App/Qiita_App/TagListPageViewController.swift
> +        cell.contentView.layer.borderColor = UIColor.gray.cgColor
Figmaと同じと思われるカラーコード#E0E0E0に指定しました。

2021-08-18 11:59 UTC, yasyun commented
> コメントしましたので確認お願いします。
> 
> 画像のキャッシュ化対策は早めにやっておいたほうが良いと思います
> (別issue)
> 
> あと、iPhone12 pro maxでビルドするとレイアウト描画おかしいのでチェックしておいてください。
> ![Aug-16-2021 09-44-53](https://user-images.githubusercontent.com/11751495/129498211-c6fca48d-585f-40bd-b8a9-cbdae7202a8d.gif)

このレイアウトが崩れてしまう現象については、セルの大きさがたまに変化してしまっている(おそらくLabelが悪さをしている)ためだと見受けたので、別でissueを作りそちらで修正してみようと思います。

2021-08-18 12:05 UTC, yasyun commented
SearchBarのクラッシュバグに対する修正をしたので、FeedPageViewController.swiftにも差分が出ています。
issueはこちらです。([SearchBarクラッシュバグ](https://github.com/shinonome-inc/mobile_sakai/issues/24))

2021-08-18 12:11 UTC, yasyun commented
画像のキャッシュ化についてのissueを立てました。[画像のキャッシュ化](https://github.com/shinonome-inc/mobile_sakai/issues/25)

2021-08-18 22:43 UTC, merged