じゃんけん課題追加
shinonome-inc/mobile_sakai pull request #3
Opened 2020-02-16 09:40 UTC by yasyun

2020-02-17 04:03 UTC, mcz9mm reviewed
コメントしました！
レイアウトの方は問題ないのでHandType周りを直してみよう！

https://dogwood008.github.io/kotlin-web-site-ja/docs/reference/enum-classes.html

https://stackoverflow.com/questions/53523948/how-do-i-create-an-enum-from-a-int-in-kotlin

2020-02-17 04:03 UTC, mcz9mm commented on jankenApp/app/src/main/java/com/example/jankenapp/MainActivity.kt
> +        enum class HandType(val id: Int) {
インデントがここから下全部ずれちゃってるよ！
四文字分ずらしてあげるとすっきり

2020-02-17 04:03 UTC, mcz9mm commented on jankenApp/app/src/main/java/com/example/jankenapp/MainActivity.kt
> +            Handler().postDelayed(Runnable {
遅延させてるの良いね。
ハンドリングもできているので大丈夫です

2020-02-17 04:03 UTC, mcz9mm commented on jankenApp/app/src/main/java/com/example/jankenapp/MainActivity.kt
> +            var cp = (0..2).shuffled().first()
enumを使ってあげると良さそうね。
intを引数にとって、ランダム値からCPをHandTypeの型として扱えるよ

```
enum class HandType(val id: Int) {
    rock(0), scisser(1), paper(2);

    companion object {
        fun fromInt(value: Int) = HandType.values().first { it.ordinal == value }
    }
}
```

2020-02-17 04:03 UTC, mcz9mm commented on jankenApp/app/src/main/java/com/example/jankenapp/MainActivity.kt
> +            var cp = (0..2).shuffled().first()
こんな感じに利用する
```
var cp = HandType.fromInt((0..2).shuffled().first())
```

2020-02-17 04:03 UTC, mcz9mm commented on jankenApp/app/src/main/java/com/example/jankenapp/MainActivity.kt
> +                when(cp){
HandTypeのcpにすると0,1,2がどの手に対応するのかwhenで書けるようになるのでここも直そう

2020-02-21 09:45 UTC, yasyun commented
コメントいただいた部分を修正したのですが、whenで結果を文字にしてwinやloseと表示する部分のコードの書き方がいけないのか、winやloseの判定が時々間違ってしまいます。確認お願いします。

2020-02-24 03:26 UTC, mcz9mm commented
AndoroidStudiでデバッグできるのでどうして、思い通りのロジックにならない原因を探ってみてみようか
https://developer.android.com/studio/debug?hl=ja

2020-02-24 03:37 UTC, mcz9mm commented
まずはジャンケンロジックの確認
・cpの値が正しいか
・handの値が正しいか
・ジャンケン部分の計算ロジックは問題ないか
・結果のwhen文は正しいか

などなど一つずつあたりをつけて調べてみよう

2020-03-12 00:48 UTC, mcz9mm requested changes
レビューしました。
あと少し！

2020-03-12 00:48 UTC, mcz9mm commented on jankenApp/app/src/main/java/com/example/jankenapp/MainActivity.kt
> +        var cp = HandType.fromInt((0..2).shuffled().first())
`var`→`val`
変更がなければ基本valで

2020-03-12 00:48 UTC, mcz9mm commented on jankenApp/app/src/main/java/com/example/jankenapp/MainActivity.kt
> +        rock(0), scisser(1), paper(2);
`scisser `→`Scissor`
タイポと、UpperCaseで書こう。

2020-03-12 00:48 UTC, mcz9mm commented on jankenApp/app/src/main/java/com/example/jankenapp/MainActivity.kt
> +        rock(0), scisser(1), paper(2);
> Rock(0),
        Scissor(1),
        Paper(2);

2020-03-12 00:48 UTC, mcz9mm commented on jankenApp/app/src/main/java/com/example/jankenapp/MainActivity.kt
> +    fun main(hand: HandType){
この`main`っていうfun名の理由は？
具体的に何を行うのかこの`main`からは伝わらないので直そう

2020-03-12 00:48 UTC, mcz9mm commented on jankenApp/app/src/main/java/com/example/jankenapp/MainActivity.kt
> +                HandType.rock -> imageView2.setImageResource(R.drawable.rock)
`imageView2`のid名も具体的にしたいかな
例えば`cpHandImageView`とか

2020-03-16 07:12 UTC, mcz9mm commented on jankenApp/app/src/main/java/com/example/jankenapp/MainActivity.kt
> +        rock(0), scisser(1), paper(2);
rock, paper が直ってないのでそこだけ修正お願いします！

2020-03-19 16:12 UTC, merged