新しいQiitApi
shinonome-inc/mobile_sakai pull request #5
Opened 2020-04-25 04:44 UTC by yasyun

2020-04-25 05:30 UTC, 175atsu commented on QiitaAPI/app/src/main/java/com/example/qiitaapi/Dataclass.kt
> +data class data(
`package com.example.qiitaapi`
1行目にはこれが必ず必要！
https://maku77.github.io/kotlin/package/basic.html

2020-04-25 05:43 UTC, 175atsu commented on QiitaAPI/app/src/main/java/com/example/qiitaapi/Dataclass.kt
> +data class data(
dataClassはAPIで取ってきたデータを入れる箱見たな扱いで
書き方は問題ないのですが
apiから取って来たデータと用意されている箱の形が一致していないので見直してみて

2020-04-25 05:59 UTC, 175atsu commented on QiitaAPI/app/src/main/java/com/example/qiitaapi/MainActivity.kt
> +    interface ItemInterface {
通信部分は大丈夫そう！

2020-04-25 06:48 UTC, 175atsu commented on QiitaAPI/app/src/main/java/com/example/qiitaapi/MainActivity.kt
> +    fun gettext(v: View){
ボタンをクリックした際の処理が書かれていると思うのだけど
ちゃんと成功しているかブレイクポイントを貼って確認してみ

2020-04-25 06:48 UTC, 175atsu reviewed
第一ヒント的に書きました

2020-05-01 05:30 UTC, mcz9mm commented on QiitaAPI/app/src/main/java/com/example/qiitaapi/Dataclass.kt
> +data class dataItem(
class名は大文字からの方が良いね
`DataItem`

2020-05-01 05:30 UTC, mcz9mm commented on QiitaAPI/app/src/main/java/com/example/qiitaapi/MainActivity.kt
> +        itemInterface.items().enqueue(object : retrofit2.Callback<dataItem> {
https://qiita.com/api/v2/items?page=1&per_page=10のレスポンスは、
`dataItem`を一つの単位として、そのListが取得できるんじゃないかな

```
{
  [
    dataItem, // 記事1
    dataItem, // 記事2
    dataItem, // 記事3
    dataItem, // 記事4
  ]
}
```

今のままだと↓↓のようなレスポンスを受け取ろうとしてる
```
{
  dataItem, // 記事1
}
```

2020-05-01 05:30 UTC, mcz9mm commented on QiitaAPI/app/src/main/java/com/example/qiitaapi/MainActivity.kt
> +        fun items(): retrofit2.Call<dataItem>
https://github.com/shinonome-inc/mobile_sakai/pull/5/files?file-filters%5B%5D=.kt#diff-e459748ca2953d9ece7cf18e2a797d57R45

これをListで受け取るようにする

`retrofit2.Callback<dataItem>`
↓↓
`retrofit2.Callback<List<dataItem>>`

2020-05-01 05:30 UTC, mcz9mm commented on QiitaAPI/app/src/main/java/com/example/qiitaapi/MainActivity.kt
> +                        if (res != null) {
responseのbodyがListになるよ

2020-05-01 05:30 UTC, mcz9mm commented on QiitaAPI/app/src/main/java/com/example/qiitaapi/MainActivity.kt
> +                        if (res != null) {
```
 if (res != null) {

}
```

nullチェックはこんな感じでも表現できる

```
response?.let {
  // itで中身(body)が参照できる
}

response?.let { res ->
  // itの名前を任意の名前(res)に変えることも可能
  // 入れ子(二重で?letを使う)の場合にitだとわかりづらくなるので注意
}
```

2020-05-01 07:03 UTC, mcz9mm reviewed
追加分

2020-05-01 07:03 UTC, mcz9mm commented on QiitaAPI/app/src/main/java/com/example/qiitaapi/MainActivity.kt
> +    fun gettext(v: View){
細かいけど
`get`と`text`は別々の単語なのでつなげるときはキャメルケースで
`getText`

2020-05-05 02:44 UTC, mcz9mm commented on QiitaAPI/app/src/main/java/com/example/qiitaapi/Dataclass.kt
> +data class User(
SerializedNameに対応するなら、、
```
data class ResponseUserModel (
    @SerializedName("id") var id: Int,
    @SerializedName("linkedin_id") var linkedinId: String,
    @SerializedName("name") var name: String,
    @SerializedName("permanent_id") var permanentId: String
)
```

2020-05-05 02:44 UTC, mcz9mm commented on QiitaAPI/app/src/main/java/com/example/qiitaapi/MainActivity.kt
> +                        var res = response.body()?.iterator()
`var`→`val`

2020-05-05 02:44 UTC, mcz9mm commented on QiitaAPI/app/src/main/java/com/example/qiitaapi/MainActivity.kt
> +        @GET("v2/items?page=1&per_page=10")
取得するページを動的に変更したいなら引数を取ってエンドポイントに変数を入れられるよ
```
@GET("v2/items?page={page}&per_page={per_page}")
fun items(@Path("page") page: Int, @Path("per_page") perPage: Int): retrofit2.Call<List<DataItem>>
```

Call
```
itemInterface.items(page = 1, perPage = 20).enqueue,,,
```

2020-05-17 12:11 UTC, mcz9mm commented on QiitaAPI/app/src/main/java/com/example/qiitaapi/MainActivity.kt
> +                WebFragment.newInstance()
```
WebFragment.newInstance(this)
```

インスタンスを作成巣だけならこれで良いよ
```
fragmentTransaction.add(
    R.id.web,
    WebFragment()
)
```

2020-06-03 02:12 UTC, mcz9mm commented
`newslist`のレイアウトの制約がうまく設定されていないので画面からはみ出してるよ

<img width="552" alt="スクリーンショット 2020-06-03 11 11 21" src="https://user-images.githubusercontent.com/11751495/83587855-01f39800-a58b-11ea-8275-7214580473e7.png">

2020-06-03 02:22 UTC, mcz9mm commented
AndroidもOSのバージョンがあって、Googleがアプリを新規で公開する場合はAPIレベルが28以上でないといけないのであげても良さそうだね。古いAPIレベルで使えない実装とかあるので。

> APK をアップロードする際は、Google Play の対象 API レベルの要件を満たしている必要があります。 新しいアプリとアプリのアップデートは、Android 9（API レベル 28）以上を対象とする必要があります。

https://developer.android.com/distribute/best-practices/develop/target-sdk?hl=ja

2020-06-03 02:37 UTC, mcz9mm commented
ごめん、最初の段階で`ListView`使ってたの気づけばよかったんだけど形としてはできているのでこのまま進めて大丈夫です。
理解だけして欲しいので、RecyclerViewとListViewの違いを調べてこのコメントに返信してくれたらオッケーにします。

2020-06-03 03:10 UTC, mcz9mm commented
記事を表示するFragmentはActivityの画面範囲全体に貼って欲しいです。
![Jun-03-2020 11-43-08](https://user-images.githubusercontent.com/11751495/83589858-6d3f6900-a58f-11ea-91bc-fda4f1beb6f1.gif)

修正点としては
・Fragment表示範囲をフレーム全体にする

だけなんだけど、Fragment(fragment_web)貼っている`FrameLayout`は背景を設定しないとデフォで透明なままなので`backgroundTint`を設定してください。(APIレベル21以上だったはず)
また、Androidにはelevation(高さ)の概念があって「記事を表示する」ボタンの高さがfragmentよりも高いと手前に表示されてしまうので、
・`activity_main`側の`FrameLayout`の`elevation`を「記事を表示する」ボタンよりも高い`elevation`を設定してみてください。

※「記事を表示する」ボタンの高さがfragmentよりも高い状態↓↓
<img width="552" alt="スクリーンショット 2020-06-03 12 01 18" src="https://user-images.githubusercontent.com/11751495/83591489-06bc4a00-a593-11ea-95b5-12d235c7f4ee.png">

2020-06-03 03:10 UTC, mcz9mm requested changes
コメントしました！

2020-06-03 03:10 UTC, mcz9mm commented on QiitaAPI/app/src/main/java/com/example/qiitaapi/MainActivity.kt
> +    private var URLs = mutableListOf<String>()
Good

2020-06-03 03:10 UTC, mcz9mm commented on QiitaAPI/app/src/main/java/com/example/qiitaapi/MainActivity.kt
>          listButton.setOnItemClickListener {parent, view, position, id ->
ListViewならこれで大丈夫です。
`setOnItemClickListener `

2020-06-03 03:10 UTC, mcz9mm commented on QiitaAPI/app/src/main/java/com/example/qiitaapi/MainActivity.kt
> +            bundle.putString("URL", url)
Bundleで値渡しうまくできてるね

2020-06-03 03:10 UTC, mcz9mm commented on QiitaAPI/app/src/main/java/com/example/qiitaapi/MainActivity.kt
> +                        var urls = mutableListOf<String>()
`var `→`val`

2020-06-03 03:10 UTC, mcz9mm commented on QiitaAPI/app/src/main/java/com/example/qiitaapi/MainActivity.kt
> +                        val res = response.body()?.iterator()
`var `→`val`
Android Studioで警告出てるかと

2020-06-08 01:50 UTC, mcz9mm commented
このコメントに返信お願いします
https://github.com/shinonome-inc/mobile_sakai/pull/5#issuecomment-637917493

2020-06-08 02:11 UTC, mcz9mm requested changes
コメントしました！

2020-06-08 02:11 UTC, mcz9mm commented on QiitaAPI/app/src/main/res/layout/activity_main.xml
> +            android:backgroundTint="@color/colorPrimary"
ここのコメントで書いてる通り、APIレベルの設定を上げないと警告出るので修正しましょう。
https://github.com/shinonome-inc/mobile_sakai/pull/5#issuecomment-637925953

![スクリーンショット 2020-06-08 10 45 42](https://user-images.githubusercontent.com/11751495/83985728-3beee080-a975-11ea-8687-0d2227a85623.png)

この辺が参考になるはず
https://feel-log.net/android/api-level-target-version-min-version/

2020-06-08 02:11 UTC, mcz9mm commented on QiitaAPI/app/src/main/res/layout/activity_main.xml
>          android:layout_width="395dp"
レイアウトの制約が絶対値での設定になっているのでここをうまく直してあげると良いです。

今の状態だと上左右の制約に対して制約がついているので下に制約追加するのと、
widthとheightを`0dp(match constraint)`に設定すれば良いはず。

![スクリーンショット 2020-06-08 11 00 13](https://user-images.githubusercontent.com/11751495/83986298-401bfd80-a977-11ea-8f4c-b61a13fa6598.png)

参考
https://qiita.com/mii-chang/items/ee965c1e8826d4e59414#widthheight

2020-06-10 07:58 UTC, yasyun commented
> ごめん、最初の段階で`ListView`使ってたの気づけばよかったんだけど形としてはできているのでこのまま進めて大丈夫です。
> 理解だけして欲しいので、RecyclerViewとListViewの違いを調べてこのコメントに返信してくれたらオッケーにします。
> 
> 課題の用件↓↓
> 
> > Require:
> > 記事一覧を表示→タップするとページ遷移し記事を表示
> > 下記のパーツを利用すること
> > Activity
> > Fragment
> > RecycerView

2020-06-10 08:28 UTC, yasyun commented
> ごめん、最初の段階で`ListView`使ってたの気づけばよかったんだけど形としてはできているのでこのまま進めて大丈夫です。
> 理解だけして欲しいので、RecyclerViewとListViewの違いを調べてこのコメントに返信してくれたらオッケーにします。
> 
> 課題の用件↓↓
> 
> > Require:
> > 記事一覧を表示→タップするとページ遷移し記事を表示
> > 下記のパーツを利用すること
> > Activity
> > Fragment
> > RecycerView

すみません、調べているうちに薄々RecyclerViewでやるのが通例なのではと感じていましたが、もうだいぶ進めてしまっていたのでListViewでやってしまいました。
ListViewとRecycerViewの大きな違いとしては、ListViewでgetItem内で行っていたもろもろの処理を、RecycerViewではそれぞれ独立させて書かなければいけないというところでしょうか。基本的にはRecycerViewの方が進化版なので、区切り線などはデフォルトではないようですが、ListViewよりも更に柔軟に、細かく実装できるのではないかと思っています。

2020-06-10 09:25 UTC, mcz9mm commented
課題とはいえ書いてある要件以外を実装してることになるので、
今度から課題の内容をよく読んでみてね。

> すみません、調べているうちに薄々RecyclerViewでやるのが通例なのではと感じていましたが、もうだいぶ進めてしまっていたのでListViewでやってしまいました。

OKです。

> ListViewとRecycerViewの大きな違いとしては、ListViewでgetItem内で行っていたもろもろの処理を、RecycerViewではそれぞれ独立させて書かなければいけないというところでしょうか。基本的にはRecycerViewの方が進化版なので、区切り線などはデフォルトではないようですが、ListViewよりも更に柔軟に、細かく実装できるのではないかと思っています。

2020-06-10 12:02 UTC, mcz9mm commented
OKです！

2020-06-10 12:02 UTC, merged